# Generated by Django 6.0.3 on 2026-03-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_subject_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='COTopicMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_mappings', to='intelligence.topic')),
            ],
            options={
                'db_table': 'co_topic_mapping',
                'unique_together': {('co_id', 'topic')},
            },
        ),
    ]
