# Generated by Django 6.0.3 on 2026-03-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_cotopicmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('IAT1', 'IAT1'), ('IAT2', 'IAT2'), ('IAT3', 'IAT3'), ('MODEL', 'MODEL'), ('SEM', 'SEM')], max_length=20)),
                ('batch', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.subject')),
            ],
            options={
                'db_table': 'student_exam',
                'unique_together': {('exam_type', 'subject', 'department', 'batch', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField()),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.cotopicmapping')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='intelligence.studentexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.student')),
            ],
            options={
                'db_table': 'student_marks',
                'unique_together': {('student', 'exam', 'co_id')},
            },
        ),
    ]
