# Generated by Django 6.0.3 on 2026-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_studentexam_studentmarks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmarks',
            unique_together={('student', 'exam', 'co')},
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
    ]
