# Generated by Django 6.0.3 on 2026-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_alter_studentmarks_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
