# Generated by Django 6.0.3 on 2026-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_studentexam_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
