# Generated by Django 6.0.3 on 2026-03-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0011_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstaffmapping',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='intelligence.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='intelligence.batch'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='intelligence.batch'),
        ),
    ]
