# Generated by Django 6.0.3 on 2026-03-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0012_alter_batchstaffmapping_batch_alter_student_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstaffmapping',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_mappings', to='intelligence.batch'),
        ),
    ]
