# Generated by Django 6.0.3 on 2026-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0013_alter_batchstaffmapping_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
