# Generated by Django 6.0.3 on 2026-03-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0014_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotopicmapping',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intelligence.subject'),
        ),
    ]
