# Generated by Django 6.0.3 on 2026-03-22 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0015_cotopicmapping_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('time_horizon_days', models.PositiveIntegerField()),
                ('daily_hours', models.FloatField()),
                ('overall_progress', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.subject')),
            ],
            options={
                'db_table': 'study_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('topic_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_links_pdf', models.URLField(blank=True, null=True)),
                ('reference_links_pdf', models.URLField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='intelligence.studyplan')),
            ],
            options={
                'db_table': 'study_plan_details',
                'ordering': ['day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
    ]
